import React from "react";
import { User } from "components/templates/User";
import Head from "next/head";

export default function UserPage() {
  return (
    <>
      <Head>
        <title>Cognito User Manager: User Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <User />
    </>
  );
}
