import React from "react";
import Head from "next/head";
import { UsersCreate } from "components/templates/UsersCreate";

export default function UsersCreatePage() {
  return (
    <>
      <Head>
        <title>Cognito User Manager: new User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UsersCreate />
    </>
  );
}
