import { Button, Space } from "antd";
import Head from "next/head";
import { Users } from "../components/Users";

export default function UsersPage() {
  return (
    <>
      <Head>
        <title>Cognito User Manager: Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Space direction="vertical" size="large">
        <Button type="primary">Create User</Button>
        <Users />
      </Space>
    </>
  );
}
